[package]
name = "vfvm-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
# Version of glam used by meshless_voronoi
glam = "0.27"
meshless_voronoi = "0.7.2"
nalgebra = "0.34.0"
num-dual = "0.13.4"
thiserror = "2.0.16"
sprs = "0.11.3"
kryst = { version = "3.2.1" }
rayon = "1.10"
log = "0.4.29"
env_logger = "0.11.9"
mimalloc = "0.1.48"

# [[bench]]
# name = "benchmarks"
# harness = false

[features]
timing = []

[dependencies.libffi-sys]
version = "2.3.0"
features = ["system"]

[profile.release]
lto = "fat"           # Enable Link-Time Optimization (LTO)
codegen-units = 1     # Optimize the whole crate at once
panic = "abort"       # Remove panic unwinding overhead
strip = true          # Strip symbols (minor binary size/cache win)